name: "Podcast Generator"
author: "Ray Villalobos"
description: "generates a feed for a podcast from yaml"
runs: 
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: the commiters email address
    required: true
    default: ${{github.actor}}@localhost
  name: 
    descriptions: the commiters name
    required: true
    default: ${{github.actor}}